CXX = g++
CXXFLAGS = -std=c++17 -Wall
LDFLAGS =

SRCS = sd1.cpp studentas.cpp
OBJS = $(SRCS:.cpp=.o)

TARGET = StudentuRusiavimas

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)
